### ISSUE TITLE
Configurable power-ups

### ISSUE THREAD

**Issue by Derek-T** [bjaraujo/Bombermaaan#22]
(Firstly, many thanks to everyone who has added to this; I have great fun with my family playing this).

This isn't a bug, but a change request... the idea - a menu option which allows the various power-ups to be turned on and off.
It would be a list of the different power-ups,  with either an on/off switch next to each, or 1 to 5 (to alter their drop frequency).

This would allow the balance of the game to be modified.

**Comment by bjaraujo** [comment]
Hi,

Thanks for the enjoying the game. It is great you have had fun with it. 

I think it is a great idea to have an extra menu to configure the popups because it is much easier and dynamic than editing the files. I will consider that for the next development phase. 

Thanks once again for the positive feedback and suggestions.
